version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - actions
      - automated
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - actions
      - automated
    groups:
      flake-inputs:
        patterns:
          - "*"
